@host = http://localhost
@port = 8000

### Registrar nuevo usuario (Admin de familia)

POST {{host}}:{{port}}/auth/register
Content-Type: application/json

{
    "email": "laura.lopez@demo.com",
    "password": "Demo1234!!",
    "full_name": "Laura Lopez"
}

### Login (Aquí obtienes el Token para el resto de pruebas)
POST {{host}}:{{port}}/auth/login
Content-Type: application/json

{
    "email": "laura.lopez@demo.com",
    "password": "Demo1234!"
}

### Obtener mis datos actuales (Verificar que el Token funciona)
GET {{host}}:{{port}}/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJjYXJsYUBkZW1vLmNvbSIsImZ1bGxfbmFtZSI6IkxhdSBNb250aXJvbmkiLCJleHAiOjE3Njk3MTgxMzF9.y_0RnqBEfYxatmuydm-c0ajc_uR8trjG4tTUyddRBHQ

### Obtener un usuario por ID específico
GET {{host}}:{{port}}/auth/users/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJjYXJsYUBkZW1vLmNvbSIsImZ1bGxfbmFtZSI6IkxhdSBNb250aXJvbmkiLCJleHAiOjE3Njk3MTgxMzF9.y_0RnqBEfYxatmuydm-c0ajc_uR8trjG4tTUyddRBHQ