@host = http://localhost
@port = 8000

"""GET children por familia"""
########

GET {{host}}:{{port}}/children/families/1/children

"""GET child por id dentro de familia"""
########GET 

GET {{host}}:{{port}}/children/families/1/children/1

"""POST create child"""
########
POST {{host}}:{{port}}/children/families/1/children
Content-Type: application/json

  {
    
    "name": "para borrar",
    "birthdate": "2019-03-09",
    "notes": "Le gusta ir a parques"
 
  }

########UPDATE  children
PUT {{host}}:{{port}}/children/families/1/children/7
Content-Type: application/json

  {
    "id": 7,
    "name": "Bianca",
    "birthdate": "2019-03-09",
    "notes": "Le gusta danza ,dibujo y jugar a las barbys"
  }

########DELETE  children
DELETE {{host}}:{{port}}/children/families/1/children/8
