@host = http://localhost 
@port = 8000

### Crear una nueva familia
POST {{host}}:{{port}}/families/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhbmEucml2ZXJhQGRlbW8uY29tIiwiZnVsbF9uYW1lIjoiQW5hIFJpdmVyYSIsImV4cCI6MTc2OTcyNjAxMH0.XlBxegjZKVbvC9j61Ox0Gmf3dxe_VCbSmEaOGu0Hf0k
Content-Type: application/json

{
    "family_name": "Familia Re"
}

### Listar MIS familias (A las que pertenezco)
GET {{host}}:{{port}}/families/my
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhbmEucml2ZXJhQGRlbW8uY29tIiwiZnVsbF9uYW1lIjoiQW5hIFJpdmVyYSIsImV4cCI6MTc2OTcyNjAxMH0.XlBxegjZKVbvC9j61Ox0Gmf3dxe_VCbSmEaOGu0Hf0k

### Obtener detalle de una familia por ID
GET {{host}}:{{port}}/families/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhbmEucml2ZXJhQGRlbW8uY29tIiwiZnVsbF9uYW1lIjoiQW5hIFJpdmVyYSIsImV4cCI6MTc2OTcyNjAxMH0.XlBxegjZKVbvC9j61Ox0Gmf3dxe_VCbSmEaOGu0Hf0k

### Actualizar nombre de la familia (Solo Admin)
PUT {{host}}:{{port}}/families/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhbmEucml2ZXJhQGRlbW8uY29tIiwiZnVsbF9uYW1lIjoiQW5hIFJpdmVyYSIsImV4cCI6MTc2OTcyNjAxMH0.XlBxegjZKVbvC9j61Ox0Gmf3dxe_VCbSmEaOGu0Hf0k
Content-Type: application/json

{
    "id": 6,
    "name": " Actualizado"
}

### Eliminar familia (Solo Admin)
DELETE {{host}}:{{port}}/families/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhbmEucml2ZXJhQGRlbW8uY29tIiwiZnVsbF9uYW1lIjoiQW5hIFJpdmVyYSIsImV4cCI6MTc2OTcyNjAxMH0.XlBxegjZKVbvC9j61Ox0Gmf3dxe_VCbSmEaOGu0Hf0k