@host = http://127.0.0.1
@port = 8000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhbmEucml2ZXJhQGRlbW8uY29tIiwiZnVsbF9uYW1lIjoiQW5hIFJpdmVyYSIsImV4cCI6MTc2OTcyNjAxMH0.XlBxegjZKVbvC9j61Ox0Gmf3dxe_VCbSmEaOGu0Hf0k
@family_id = 1
@member_id = 1

### Crear evento
POST {{host}}:{{port}}/events/families/{{family_id}}/members/{{member_id}}/events
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "Cena Familiar",
  "description": "Cena en casa",
  "location": "Casa",
  "type": "family",
  "start_at": "2026-02-15T21:00:00",
  "end_at": "2026-02-15T22:30:00"
}

### Obtener todos los eventos de la familia
GET {{host}}:{{port}}/events/families/{{family_id}}
Authorization: Bearer {{token}}

### Obtener un evento por ID
GET {{host}}:{{port}}/events/families/{{family_id}}/events/1
Authorization: Bearer {{token}}

### Actualizar evento
PUT {{host}}:{{port}}/events/families/{{family_id}}/events/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 1,
  "title": "Cena Familiar Actualizada",
  "description": "Traer postre",
  "location": "Casa",
  "type": "family",
  "start_at": "2026-02-15T21:30:00",
  "end_at": "2026-02-15T23:00:00"
}

### Eliminar evento
DELETE {{host}}:{{port}}/events/families/{{family_id}}/events/1
Authorization: Bearer {{token}}
